### ISSUE TITLE
Question about the DCC-GARCH connectedness method.

### ISSUE THREAD

**Issue by Richard-2038** [GabauerDavid/ConnectednessApproach#10]
Hi, i'm studying connectedness methods and your package helps a lot! I have a question about the DCC-GARCH connectedness method. In your paper, VIRF is computed as the difference between two conditional expectation. While in the R program, it can be derived by only computing the first conditional expectation if  "standardized" is set to be "False", and it seems that the empirical part of your paper uses this setting. I can't understand how does it match the formula in the paper. Could you please explain the meaning of this argument and why it makes sense to set it to be "False"?

thank you
regards

**Comment by GabauerDavid** [comment]
Hi Richard,
Thanks a lot for your kind words. 
You are right and this is a mistake I am aware of. I have just seen that I have not uploaded the latest version of the replication files where I described this issue. 
Will upload the latest replication files as soon as possible.
Sorry for the inconvenience this may have caused. 
Best,
David
