### ISSUE TITLE
command "SummaryStatistics" give this error, how to solve it?

### ISSUE THREAD

**Issue by lan-slot** [GabauerDavid/ConnectednessApproach#11]
Dear prof:

When i use my own data, this command "SummaryStatistics" give this error: "Error in if (pval > 1) pval <- 2 - pval : 
  missing value where TRUE/FALSE needed",  how can i fix this and get the statistic results. By the way, i have no missing values in my zoo data matrix.

**Comment by lan-slot** [comment]
I found the problem, the zoo data matrix should not include the date(time), then the "SummaryStatistics" works fine.

**Comment by GabauerDavid** [comment]
Dear Ian,
Please be so kind and send me the dataset so I can replicate the error:
david.gabauer@hotmail.com
Best,
David

**Comment by GabauerDavid** [comment]
As discussed via E-Mail, the error is caused by the function moments::anscombe.test(). Since I am not the developer of this package it is out of my hand to fix the bug. Nevertheless, the developer has been contacted and I created a workaround that fixes the error in the meanwhile.

**Comment by lan-slot** [comment]
Got it! Thank you so much, hope the developer of 'moments' can upgrade it soon.
