### ISSUE TITLE
Problem with QVAR estimation and Summary Statistics ERS Significance value

### ISSUE THREAD

**Issue by tasfiq13** [GabauerDavid/ConnectednessApproach#12]
After recent update I am failing to run QVAR or TF-QVAR model. Even I have tried with sample code as follows:

```
data("gcat2022")
partition = c(pi+0.00001, pi/5, 0)
dca = ConnectednessApproach(gcat2022, 
                            model="QVAR",
                            connectedness="Frequency",
                            nlag=1,
                            nfore=100,
                            window.size=200,
                            Connectedness_config = list(
                              FrequencyConnectedness=list(partition=partition, generalized=TRUE, scenario="ABS")
                            ))
```
                            
The error I am getting as follows:

```
Estimating model
Error in if (method == "model.frame") return(mf) : 
  argument is of length zero
```

About the summary statistics, the ERS unit root test is not providing significance *. 

for example : `SummaryStatistics(cgs2021)`

**Comment by GabauerDavid** [comment]
Hi Tas,
I just run the code and I do not face any issue.
Please try to update the package using the following lines of code:
library("devtools")
install_github("GabauerDavid/ConnectednessApproach")
Furthermore, you are loading the gcat2022 dataset and then you want to get the Summary Statistics of cgs2021 without loading it. That might cause the second issue.

**Comment by tasfiq13** [comment]
Hello David,

Thanks for quick your response. However, I am facing the same issue after the installation. Let me try a fresh installation by uninstalling R. I will get back to you soon.

About the Summary Statistics I just give an example. It was same for all data. 

Thanks

**Comment by tasfiq13** [comment]
Hi David,
I have figured out the problem. Latest version of ConnectednessApproach requires MatrixModels package. 
After a fresh installation of R everything is working fine including Summary Statistics.
Thanks again
