### ISSUE TITLE
QVAR bug: missing method in QVAR

### ISSUE THREAD

**Issue by dan-bart** [GabauerDavid/ConnectednessApproach#13]
Hi David,

I came across similar problem to one that was already [mentioned](https://github.com/GabauerDavid/ConnectednessApproach/issues/12#issue-1828004812). But I believe that the bug is still there.

**Replication:**

```R
library(devtools)
install_github("GabauerDavid/ConnectednessApproach", force = T)
library(ConnectednessApproach)
data("dy2012")
dc_q95 = ConnectednessApproach(dy2012,
                               model="QVAR",
                               connectedness="Time",
                               nlag=1,
                               nfore=100,
                               VAR_config=list(QVAR=list(tau=0.95, method="fn")))
```

Throws error:
```
Estimating model
Error in if (method == "model.frame") return(mf) : 
  argument is of length zero
```

**Explanation:**

So when you choose the QVAR method, ConnectednessApproach.R sets the configuration as [such](https://github.com/GabauerDavid/ConnectednessApproach/blob/0ca4799a2f5aa68fdd2c4a3e8a2e0e687d0a9b17/R/ConnectednessApproach.R#L113), without passing on the 'method' argument for quantile regresssion :
```R
var_model = QVAR
configuration = list(nlag=nlag, tau=VAR_config$QVAR$tau)
```

The configuration of QVAR.R then takes the parameters from the configuation, but since the configuration was overwritten, the configuration$method does not exist, and `method` gets set to NULL:
```R
QVAR = function(x, configuration=list(nlag=1, tau=0.5, method="fn")) {
  tau = as.numeric(configuration$tau)
  nlag = as.numeric(configuration$nlag)
  method = as.character(configuration$method)
```

you then pass method=NULL to the [rq](https://github.com/GabauerDavid/ConnectednessApproach/blob/0ca4799a2f5aa68fdd2c4a3e8a2e0e687d0a9b17/R/QVAR.R#L44C5-L44C61) and the rq crashes on[ this line](https://github.com/cran/quantreg/blob/d61d5ebf4d6a933432e36fddb54fabd84e4cdc39/R/quantreg.R#L107C18-L107C31)
```R
fit = rq(z[,i] ~ z[,-c(1:k)], tau=tau[i], method=method)
```

If I have time, I will create a PR for this, but I am sure you could fix it quicker.

Thanks for the package, it greatly eases my PhD studies :)

**Comment by GabauerDavid** [comment]
Hi Daniel,
Thanks a lot for pointing this out. 
I am already aware of this issue and will take care of it as soon as I am back from my vacation.
Best,
David
