### ISSUE TITLE
adjust graphics parameters

### ISSUE THREAD

**Issue by in131313** [GabauerDavid/ConnectednessApproach#14]
Hi，professor：
         I'd like to adjust the rows and columns，but they are not graphics parameters. How can I solve this problem?
Thank you so much!

**Comment by lan-slot** [comment]
I don't know what u exactly mean by rows and columns, but I think using this code:

write.xlsx(dca$TABLE, "your path/document name.xlsx")

will put the result of dca in the example into Excel file, and then u can adjust them in Excel.

**Comment by in131313** [comment]
![1712580207936](https://github.com/GabauerDavid/ConnectednessApproach/assets/149661523/3fb64ba0-cbf1-40df-875a-f9314e2700a8)
I mean how can i adjust this graph‘s cols and rows.
I thank you very much for your kind assistance.
