### ISSUE TITLE
Package cannot be installed in R

### ISSUE THREAD

**Issue by souritzgithub** [GabauerDavid/ConnectednessApproach#15]
The package as cited in the GIt hub cannot be installed in R.

Please Help.

**Comment by lan-slot** [comment]
Hi, u should upload the screenshot of error reporting interface, else we will do not know your exactly problem. Usually, following step 2: 

library(devtools)
install_github("GabauerDavid/ConnectednessApproach")

Running these two lines of code can successfully install this package.

**Comment by souritzgithub** [comment]
Thanks. I just want to ask whether the package can also include the Connectedness on the frequency domain ( similar to the paper by Barunik and Khrelik, 2018)Regards,Sourit DasOn 24 Mar 2024, at 19:00, lan-slot ***@***.***> wrote:﻿
Hi, u should upload the screenshot of error reporting interface, else we will do not know your exactly problem. Usually, following step 2:
library(devtools)
install_github("GabauerDavid/ConnectednessApproach")
Running these two lines of code can successfully install this package.

**Comment by GabauerDavid** [comment]
The frequency connectedness approach of Barunik and Krehlik (2018) is also implemented. Please see the example files:
https://gabauerdavid.github.io/ConnectednessApproach/2018BarunikKrehlik

**Comment by souritzgithub** [comment]
Thank you so much 👍Regards,Sourit DasOn 17 May 2024, at 15:02, David Gabauer ***@***.***> wrote:﻿
The frequency connectedness approach of Barunik and Krehlik (2018) is also implemented. Please see the example files:
https://gabauerdavid.github.io/ConnectednessApproach/2018BarunikKrehlik
