### ISSUE TITLE
Detecting statistically significant changes in connectedness of Greenwood-Nimmo et al. (2024)

### ISSUE THREAD

**Issue by Jhuang-pku** [GabauerDavid/ConnectednessApproach#17]
Dear Professor, thank you for your tremendous contribution to extending the spillover index developed by Diebold and Yilmaz (2009, 2012, 2014) which has been widely used to analyze and quantify changes in financial market connectedness. Yet despite its popularity, formal statistical evidence of how connectedness responses to adverse events is absent.
Greenwood-Nimmo et al. (2024) address this issue by developing a non-parametric bootstrap-after-bootstrap framework that supports formal probabilistic analysis of changes in the spillover index. The authors also provide source codes in Gauss which, however, are not that convenient for replications and applications. It would be nice if you can kindly consider to incorporate the Greenwood-Nimmo et al. (2024) model into the Connectedness Approach. The attached files are the pdf of Greenwood-Nimmo et al. (2024) and relevant codes for replications in Gauss and hopefully useful for you.
[Detecting statistically significant changes in connectedness.pdf](https://github.com/user-attachments/files/17728453/Detecting.statistically.significant.changes.in.connectedness.pdf)
[GKN_Event_replication.zip](https://github.com/user-attachments/files/17728459/GKN_Event_replication.zip)

**Comment by GabauerDavid** [comment]
Thanks so much for your kind words.
I am well aware that there are multiple connectedness approaches not covered by the provided R package. However, please keep in mind that creating and maintaining the package over the years has been a free service I offered to the research community. Unfortunately, I simply do not have the time to implement all proposed connectedness approaches. That said, I do provide the code for the estimation processes used in my own papers, allowing researchers to leverage them. I would suggest reaching out to the authors of other papers to request their codebases. If you plan to use a specific methodology for one of your research papers, I kindly ask that you implement it yourself.
