### ISSUE TITLE
How to add a legend to the plot ?

### ISSUE THREAD

**Issue by extrazxy** [GabauerDavid/ConnectednessApproach#18]
Dear Professor, thanks to your respectful work, I have a chance to do my connectedness research as a beginner(both in connectedness and in R). 

When I replicate the TVP-VAR connectedness approach in your tutorial, I wonder if there is a way to add a legend to the plot since there are several colored lines besides the black region. Actually I also have some trouble in interpretion of these lines because there are four currencies in the dataset but only three colored lines in all the plots.
![image](https://github.com/user-attachments/assets/99c515d9-1c78-4bdf-927b-bb0a78ce3d07)

Sincerely appreciate your package!

**Comment by GabauerDavid** [comment]
Currently, I do not have time, however, as soon as I update the package, I will incorporate it.
