### ISSUE TITLE
network graphs

### ISSUE THREAD

**Issue by usama0990** [GabauerDavid/ConnectednessApproach#5]
hi,
i have done related work on connectedness among different financial markets but one thing that is left are the network diagrams. i need directions for that, plz someone help.

**Comment by GabauerDavid** [comment]
Please see for this purpose the function PlotNetwork. As input it just needs a connectedness object (dca) and whether you would like to illustrate the net pairwise directional connectedness (NPDC) or pairwise connectedness index (PCI).
