### ISSUE TITLE
Query about plotting asymmetric connectivity indices 

### ISSUE THREAD

**Issue by ghost** [GabauerDavid/ConnectednessApproach#6]
I follow the tutorial on "Crude oil and Islamic sectoral stocks: Asymmetric connectedness and investment strategies" and found that the colors used by the function 'PlotTCI()' are inverted. The function plot the negative returns in color green and the positive in color red. I also checked it with the tutorial and the official publication. Just be cautious or invert the order of the elements of the list resulting from the connectivity indices calculaiton DCA[[1]]. 

Regards, 
Javier Emmanuel Anguiano Pita

**Comment by GabauerDavid** [comment]
Dear Javier,
If you want the colors to be changed you just need to change the ordering using RColorBrewer or change the order like this: PlotTCI(DCA[[1]], ca=list(DCA[[3]], DCA[[2]]), ylim=c(50,100)). As long as the results and their interpretations are the same as in the paper I don’t see any reason to adjust the R package. Nevertheless, I would like to thank you for pointing out the color difference.
