### ISSUE TITLE
how to draw quantile net pairwise connectedness using the model in the paper Interest rate swaps and the transmission mechanism of monetary policy: A quantile connectedness approach

### ISSUE THREAD

**Issue by Philip-Cao-9527** [GabauerDavid/ConnectednessApproach#7]
Dear Professor, 
I'm wondering how to draw quantile net pairwise connectedness, while in the paper, the author only draws the total connectedness and the net total connectedness. It will be highly appreciated if you can tell me how to write the code. Because the net pairwise connectedness is 3-dimention, which increases the difficulty to write the code.
warm regards！

**Comment by GabauerDavid** [comment]
Dear Nick,
It should work exactly like the net (quantile) total connectedness plots in our Economics Letters publication. You need a heat map where on the y-axis you have quantiles and on the x-axis time. As the colors of the heat map illustrate the net pairwise connectedness value you cover all 3 dimensions. 
Best
David
