### ISSUE TITLE
nfore parameter doesn't work when using ElasticNet Model

### ISSUE THREAD

**Issue by Jizhou625** [GabauerDavid/ConnectednessApproach#8]
**Problem**: nfore parameter doesn't work when using ElasticNet Model

**Key words**: nfore param; Variance decomposition; ElasticNet 

**Reproduction**: I am using the ConnectedApproach api. When I set model="VAR", the "nfore = n" parameter works, it returns the correct forecast error variance decomposition with forecast step n. 
However, when I set model="LASSO"/"Ridge"/"Elastic", the nfore parameter doesn't work. I tried to change nfore from 1-10, but it reports the same forecast error variance decomposition result. 
Is this function not yet fully implemented? 

**Codes**: 
![1680429710329](https://user-images.githubusercontent.com/116972032/229346074-3e71e220-2b98-4e34-a679-2af2cd9256c8.png)

Thank you

**Comment by GabauerDavid** [comment]
Dear Jizhou,
As I am currently without laptop it is difficult for me to reproduce your error. Just by going through the code I could not spot an error. The GFEVD is a separate function which uses the VAR coefficient and variance covariances matrix and is the same for all models. According to the code the ElasticNet VAR should work. If not you should get a different error message. Please fix nfore to a specific number to avoid that n gets updated and is always the same number. 
Best,
David

**Comment by Jizhou625** [comment]
Thank you for your reply, I think the est_elastic$table should report the forecast error variance decomposition with forecast step $n$. When $n$ is different, the result should be different. But using model="Elastic", I change nfore but the est_elastic$table always keeps the same. (model="VAR" is correct).

**Comment by Jizhou625** [comment]
When I say change nfore, I mean I try to estimate the model for ten times and each time with a different $n$. But the result of FEVD always keeps the same

**Comment by Jizhou625** [comment]
Oh, I think I can use the FEVD function by myself instead of using est_elastic$table  to calculate the FEVD result. Thank you

**Comment by Jizhou625** [comment]
It seems there is something wrong with my data. The coefficients of my ElasticNet VAR are all reduced to 0. The code is right, Thank you very much for the help

**Comment by GabauerDavid** [comment]
Always welcome!
