### ISSUE TITLE
Question about "PlotNetwork" command.

### ISSUE THREAD

**Issue by lan-slot** [GabauerDavid/ConnectednessApproach#9]
First of all, so nice, this package works very well. 
Secondly, as a research beginer, I would like to ask how the network pic drawn by "PlotNetwork(dca, method="NPDC")" should be interpreted, e.g. how is the thickness of the lines determined, what is the meaning of the directional line, and what does it mean if there are no lines connected between two nodes, as I have not found any relevant references, so I am here...

**Comment by GabauerDavid** [comment]
Hi Ian,
Thanks a lot for your kind words. 
NPDC stands for the net pairwise directional connectedness. The connectedness table shows how much variable i influences variable j as well as how much variable j influences variable i. In case the impact variable j has on variable i is larger than vice versa you will see an arrow from variable j to variable i. As you have k variables in the network the magnitude of those net transmissions might differ substantially. Thus, a minmax normalization is used. Please keep in mind that all NPDC values are positive. Therefore, after minmax normalization all values - and consequently the thickness of the lines are within zero and unity. The threshold (default=0.25) means that all values below 0.25 are set to zero as researchers might not be interested in irrelevant NPDCs. In the event that all NPDC should be illustrated the threshold needs to be set to zero. Thus, the NPDC network plot illustrates the relative NPDC of the investigated propagation mechanism. 
I hope that this explanation is helpful. 
Best,
David

**Comment by lan-slot** [comment]
Got it, Thank you so much for your detailed reply!
